### ISSUE TITLE
Backport Rails 5 compatiblity

### ISSUE THREAD

**Issue by maschwenk** [Houdini/two_factor_authentication#118]
Is there any way you could backport  this commit: https://github.com/Houdini/two_factor_authentication/commit/fd7e18c2eac7273b4fd76c882b26b9ad1723a1cb to 1.x? 2.x seems to have been in progress for a while and it'd be nice to be Rails 5 compatible in the meantime.

**Comment by Houdini** [comment]
Please, check the version 2.0.
I've just published it.
