### ISSUE TITLE
"Upgrading from version 1.X to 2.X" section of the README file

### ISSUE THREAD

**Issue by edsimpson** [Houdini/two_factor_authentication#119]
In the [Upgrading from version 1.X to 2.X](https://github.com/Houdini/two_factor_authentication/blob/master/README.md#upgrading-from-version-1x-to-2x) section of the README file, I don't understand this sentence:
> The otp_secret_key is not only required for users who use Google Authentictor, so unless it has been shared with the user it should be set to nil.

I'm happy to help reword it, but I need to understand better what the condition is for setting the property to nil.

Thank you.

**Comment by Houdini** [comment]
The idea is that the field _otp_secret_key_ is only relevant for users with two factor authentication.

For any other users it useless.

**Comment by fulstop** [comment]
This sentence is terribly confusing. I am also stuck digging through the code to understand what is meant by this. That being said, I still can't get Google Authenticator auth working, even after creating the provisioning uri and saving the code to my app. This documentation needs to be greatly improved for onboarding; I sense there are quite a few holes.

**Comment by Houdini** [comment]
@fulstop Could you please help with the documentation?

**Comment by fulstop** [comment]
@Houdini I definitely would, but I still don't fully understand the intended implementation.

**Comment by edsimpson** [comment]
I'll make a tweak to the part I didn't understand and submit a pull request.

**Comment by edsimpson** [comment]
@Houdini merged my document tweak. Thank you! Closing this issue.
