### ISSUE TITLE
Can't create otp_secret_key

### ISSUE THREAD

**Issue by ManuelFrigerio** [Houdini/two_factor_authentication#152]
Hi,

Mine is a standard use case: users can choose to enable/disable 2FA from their settings.
When they do enable it, I want to be able to generate a QR code for my users to associate my app with their Google Authenticator one.

In the Readme, you have this bit:

This gem is compatible with Google Authenticator. To enable this a shared secret must be generated by invoking the following method on your model:

    user.generate_totp_secret

This must then be shared via a provisioning uri:

    user.provisioning_uri # This assumes a user model with an email attribute

The problem for me is that it's not clear at all what that means.
I've tried to call user.provisioning_uri on a user, just to get the error

    provisioning_uri called with no otp_secret_key set

I then proceed in creating otp_secret_key (btw, there is no reference in the Readme in how to create it) in several ways

    user.otp_secret_key = user.generate_totp_secret
    user.otp_secret_key = SecureRandom.random_bytes(32)

But it doesn't matter what I do, I always get the same error:

    ArgumentError: key must be 32 bytes or longer

Can you please help me figure out how to fix this?

Thanks

**Comment by fzf** [comment]
@ManuelFrigerio this is a configuration issue vs an issue with the key that is generated, you need to ensure that the `otp_secret_encryption_key` in your `devise.rb` is longer then 32 characters:

```
  config.otp_secret_encryption_key = 'string_that_is_longer_then_32_characters'
```

Let me know if that fixes it for you
