### ISSUE TITLE
Need to upgrade or lock rotp at v3.x

### ISSUE THREAD

**Issue by mindtonic** [Houdini/two_factor_authentication#158]
rotp introduces breaking changes in version 4 [https://github.com/mdp/rotp#breaking-changes-in--40].

**Comment by aariveros** [comment]
I found a problem with the otp verification. The verify_with_drift_and_prior call is broken, so I made a branch with a fix as an alternative to lock rotp:
https://github.com/resitcl/two_factor_authentication/commit/d462080c479825da2fcd27acf38c9dddd0a6ae78

I'm using rails 5.2, rotp 4.0.2. It seems to be the only problem that the upgrade introduces.

**Comment by kchasel** [comment]
Also ran into this issue. We downgraded to 3.3.1 to resolve but applying the above patch to upgradae this library to support rotp >= 4.0 would be great!

**Comment by Migoo** [comment]
Same here. An update would be graciely appreciated

**Comment by aariveros** [comment]
#159

**Comment by mindtonic** [comment]
Wonderful! Thank you.
