### ISSUE TITLE
Security enhancements

### ISSUE THREAD

**Issue by vilda** [Houdini/two_factor_authentication#51]
Just to mention that there are two good practices that are missing in this library. Worth considering their implementation to improve security.

First one is required by RFC 6238 - authentication code once accepted must not be accepted twice (i.e. again). This requires additional field in DB.

Second one is a best practice, also recommended by RFC 6238 - encrypt security key in DB. The encryption key must not be stored in DB. One-way hash functions like scrypt cannot be used for TOTP, but simple encryption would suffice.

(Also note there is by mistake used term "authorisation" in README.)

**Comment by kiote** [comment]
hi, @vilda 

Having any ideas about gem which follows that practice you've mentioned? 

I'm looking for good 2-factor-auth library now and didn't find any yet.

**Comment by vilda** [comment]
@kiote All gems I found were missing some of those desired properties. However, there is https://github.com/tinfoil/devise-two-factor which encrypts data in DB and they actually implemented code-reuse-avoidance when I opened a ticked for it. It seems maintained, worth checking out.

**Comment by kiote** [comment]
Thanks for suggestion, Viliam! 

Tried that one, but faced with https://github.com/tinfoil/devise-two-factor/issues/52.

**Comment by monfresh** [comment]
I've been working on a pull request for encrypting the OTP. It should be done today.

**Comment by kiote** [comment]
awesome! I'm going to have a looong holidays soon, but hopefully will have a time to try out your solution/fix! Thanks!

**Comment by waiting-for-dev** [comment]
Aren't these security flaws already fixed?

**Comment by Houdini** [comment]
Yes, these security issues are fixed in commits:
https://github.com/Houdini/two_factor_authentication/commit/2df6fa248192f409526bc06b59d02e8655a20839
https://github.com/Houdini/two_factor_authentication/commit/d2b6d39d2419fc5fc78bea1b1889d8277f679f80
