### ISSUE TITLE
Do we have any two_factor_method like authenticate_user!

### ISSUE THREAD

**Issue by ashvushinde** [Houdini/two_factor_authentication#58]
I need to to authenticate a user is two-step authenticated or not.
As in simple devise we had a method like 
``` authenticate_user! ```

I need to set this in before_action filter.
Can we have similar method for two-factor-authentication?

**Comment by Houdini** [comment]
You can use 
```ruby
def need_two_factor_authentication?(request)
  request.ip != '127.0.0.1'
end
```
in user model. Is this what you need?

**Comment by ashvushinde** [comment]
Not this actually.  
 
- if user_signed_in?  
  #Some HTML part

So the issue is i need a method which will be equivalent like this. Because it still shows the header and sidebar while we are inserting the OTP to the HTML view.  
Ideally while entering the OTP, the header and sidebar should not displayed because user has not completely signed in.
Am i missing something here ?

**Comment by Houdini** [comment]
Ough, yes.
Please check method 
```ruby 
is_fully_authenticated?
```
it's exactly controller helper.
