### ISSUE TITLE
attr_encrypted gem is not working with two_factor_authentication gem

### ISSUE THREAD

**Issue by tarujain20** [Houdini/two_factor_authentication#74]
Hi 

I am already using attr_encrypted gem. I want to use two_factor_authentication gem. 

But I get the following error whenever user is saved:

ArgumentError - wrong number of arguments (2 for 1):
  attr_encrypted (1.3.4) lib/attr_encrypted.rb:143:in `block (2 levels) in attr_encrypted'

Is two_factor_authentication gem supposed to work well with 'attr_encrypted', '~> 1.3.4' gem?

**Comment by Houdini** [comment]
Hello,

please tell me more how do you use this gem?
two_factor_authentication supports encrypted: true option, so it's better to use native option.

I'll close this issue for now, please free to open it if you have any questions.
