### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by iDiogenes** [Houdini/two_factor_authentication#82]
It would appear that the changes added in 1.1.5 are a little more significant than a patch level change. Support for ruby 1.9.3 is dropped and the addition of the Encryptor gem will break functionality for any anyone who has a custom Encryptor lib, such as myself. What was the reasoning for not making this a 1.2 release? It seems like it might have been better suited for a 1.2 as existing functionality breaks with the changes 1.1.5, which should not be the case with patch level changes.

**Comment by joaoribeirost** [comment]
And there were new changes now that aren't installed through Ruby Gems, only through github install.

**Comment by Houdini** [comment]
@joaoribeirost Actually current version in github is almost version 2.0, soon will be available at Ruby Gems.

**Comment by Houdini** [comment]
@iDiogenes On one side I agree with, on other ruby 1.9.3 is long time outdated version.
Do you still need version 2.0 for 1.9.3?

**Comment by radsaq** [comment]
On the same note, it would be nice to get an updated ~1.1.x version with just the warden hook fix and not the pre-2.0 changes to internals.

**Comment by gbrl** [comment]
I'm using rails 5, and the only way I could get this gem working was to point my Gemfile src to github. The current version that rubygems is hosting does not work with Rails 5. It would be good to update the README. I will do a PR. However, the gem doesn't work 100% with Rails 5 either, as I've outlined in issue #104

**Comment by gaurish** [comment]
Any Plan to do a release?

**Comment by therrick** [comment]
I'm also anxiously awaiting a 2.0 release. Is there a list anywhere of breaking changes since v1.1.5 or upgrade requirements?

**Comment by Houdini** [comment]
Done
